# Generated by Django 4.0.4 on 2022-05-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs', models.IntegerField()),
                ('larvae', models.IntegerField()),
                ('sealed_brood', models.IntegerField()),
                ('covered_bees', models.IntegerField()),
                ('nectar_honey', models.IntegerField()),
                ('pollen', models.IntegerField()),
                ('pest_spotted', models.CharField(max_length=200)),
                ('pest_action', models.CharField(max_length=200)),
                ('notes_concerns', models.CharField(max_length=300)),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hive.hive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
