# Generated by Django 4.0.4 on 2022-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_alter_hive_hive_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='hive_number',
            field=models.IntegerField(),
        ),
    ]
